AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FastApiApp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 512
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY