AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyFastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10 
      Handler: app.handler
      CodeUri: ./CodingTest 
      Policies: 
        - AmazonRDSFullAccess
      Environment:
        Variables:
          DATABASE_HOST: ...
          DATABASE_USER: ... 
          DATABASE_PASSWORD: ...
          DATABASE_NAME: ...
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: / 
            Method: ANY 