AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Coding Test for 3Bee

Globals:
  Function:
    Timeout: 30

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      Runtime: python3.12
      CodeUri: ./app
      Environment:
        Variables:
          DATABASE_URL: ...
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: testdb
      Engine: mysql
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      MasterUsername: user
      MasterUserPassword: password